#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
use File::Basename;
use File::Path;

#--------------------------------------------------
# actions for nethserver-iaxmodem-update event
#--------------------------------------------------

my $event = "nethserver-iaxmodem-update";

event_actions($event, 'initialize-default-databases' => '00');

event_services($event, 'iaxmodem' => 'restart');


#--------------------------------------------------
# actions for nethserver-iaxmodem-save event
#--------------------------------------------------

$event = "nethserver-iaxmodem-save";

event_actions($event, 'nethserver-iaxmodem-modemsetup' => 20);

event_services($event, 'iaxmodem' => 'restart');


#--------------------------------------------------
# actions for nethserver-hylafax-update event
#--------------------------------------------------

my $event = "nethserver-hylafax-update";

event_actions($event, 'nethserver-iaxmodem-hylasetup' => '30');


#--------------------------------------------------
# actions for nethserver-hylafax-save event
#--------------------------------------------------

my $event = "nethserver-hylafax-save";

event_actions($event, 'nethserver-iaxmodem-hylasetup' => '30');

