#!/usr/bin/perl

#
# Copyright (C) 2017 Nethesis S.r.l.
# http://www.nethserver.org
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

# Fix for https://github.com/NethServer/dev/issues/5344

use strict;

use esmith::DB::db;
my $modemsDb = esmith::DB::db->open('modems') || die("Could not open destination modems db\n");

foreach my $modem ($modemsDb->get_all_by_prop('type' => 'iax')) {
    my $extension = $modem->prop('extension') || next;
    my $faxdevice = "ttyIAX$extension";
    system("/usr/bin/systemctl enable hylafax-faxgetty@".$faxdevice.".service");
}
