#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use esmith::DB::db;
use strict;

my $modemsDb = esmith::DB::db->open('modems') || die("Could not open destination modems db\n");

# cleanup iaxmodem configuration
my @configs = glob('/etc/iaxmodem/*');
unlink @configs;

my $port = 4570;
foreach my $modem ($modemsDb->get_all_by_prop('type' => 'iax')) {
    my $peername = $modem->prop('extension') || "";
    next unless ($peername ne "");
    my $device = "/dev/ttyIAX".$peername;
    my $server = $modem->prop('server') || "localhost";
    my $secret = $modem->prop('password') || "";
    my $cidname = $modem->prop('cidName') || "";
    my $cidnumber = $modem->prop('cidNumber') || "";
    generate_iaxmodem_conf($peername, $device, $server, $secret, $cidname, $cidnumber,$port);
    $port++;
}


# Create iax modem configuration file
sub generate_iaxmodem_conf()
{
    my $peername = shift;
    my $device = shift;
    my $server = shift;
    my $secret = shift;
    my $cidname = shift;
    my $cidnumber = shift;
    my $port = shift;

    my $template = "device     %s
owner      uucp:uucp
mode       660
port       %s
refresh    60
server     %s
peername   %s
secret     %s
cidname    %s
cidnumber  %s
codec      slinear
";
    my $content = sprintf($template,$device,$port,$server,$peername,$secret,$cidname,$cidnumber);
    my $file = "/etc/iaxmodem/ttyIAX".$peername;
    open (FILE, ">$file") or die "Cannot create file: $file\n";
    print FILE $content;
    close (FILE);
}

exit 0;

